### ISSUE TITLE
parent_id

### ISSUE THREAD

**Issue by tgoeminne** [josbeir/image#7] opened 2017-02-21 04:24 UTC
HI,

I am wonder how the relation is defined for this model? 

I have an article and then parent_id, when I want to collect the main article with children, the images are not bound to the children?

Greets,
Thomas

**Comment by tgoeminne** [comment] 2017-02-24 02:35
Is this plugin dead????

**Comment by tgoeminne** [comment] 2017-02-24 02:41
See example:

$this->belongsTo('Variations', [
        	'className' => 'Articles',
        	'foreignKey' => 'parent_id'
        ]);

Then when search for articles and use contain => Variations.images, the images show up as empty...

**Comment by josbeir** [comment] 2018-06-15 09:40
Not dead, just a bit dorment :-) 

Its a bit unclear what the issue is, could you maybe include a full snippet of what you did and you expect to happen?

**Comment by tgoeminne** [comment] 2018-06-15 09:43
Hi,

It's been a while. I have managed to get everything to work the way I wanted it. I don't actually remember anymore since it's so long...

Gr

**Comment by josbeir** [comment] 2018-06-15 09:47
Alright! I'll close it then

**Closed as completed by josbeir** 2018-06-15 09:47 UTC
